# Generated by Django 5.2.6 on 2026-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caducidadproducto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='caducidadproducto',
            name='informacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
