[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py *_tests.py
addopts = -v
python_files = test_*.py *_tests.py tests.py
addopts = -v --cov=apps --cov-config=.coveragerc --cov-report=term-missing --cov-fail-under=90

markers =
    e2e: pruebas end-to-end con Playwright
